# Do not edit this file, it is automatically generated when app.py; is executed last run 2022-01-04 17:49:27.723113

from enum import Enum


class BotName(str,Enum):
	bubblebot = 'bubblebot',
	bubblebot_v2 = 'bubblebot_v2',
	bubblebot_v3 = 'bubblebot_v3',
	bubblebot_v4 = 'bubblebot_v4',
	buzzkillbot = 'buzzkillbot',
	originaltestbot = 'originaltestbot',
