# Do not edit this file, it is automatically generated when app.py; is executed last run 2022-01-12 08:00:21.352576
 
from enum import Enum


class BotName(str,Enum):
	bubblebot = 'bubblebot',
	bubblebot_v2 = 'bubblebot_v2',
	bubblebot_v3 = 'bubblebot_v3',
	bubblebot_v4 = 'bubblebot_v4',
	bubblebot_v5 = 'bubblebot_v5',
	buzzkillbot = 'buzzkillbot',
	buzzkillbot_v2 = 'buzzkillbot_v2',
	originaltestbot = 'originaltestbot',
