# Do not edit this file, it is automatically generated when app.py; is executed last run 2022-04-22 21:10:49.664242
 
from enum import Enum


class BotName(str,Enum):
	bubblebot_v1 = 'bubblebot_v1',
	bubblebot_v2 = 'bubblebot_v2',
	bubblebot_v3 = 'bubblebot_v3',
	bubblebot_v4 = 'bubblebot_v4',
	bubblebot_v5 = 'bubblebot_v5',
	bubblebot_v6 = 'bubblebot_v6',
	buzzkillbot_v1 = 'buzzkillbot_v1',
	buzzkillbot_v2 = 'buzzkillbot_v2',
	originaltestbot_v1 = 'originaltestbot_v1',
	bubblebot = 'bubblebot',
	buzzkillbot = 'buzzkillbot',
	originaltestbot = 'originaltestbot',
	Alphabot = 'Alphabot',
