@startuml
allow_mixing
entity "Tom"
entity "Graig"
entity "Jeannine"

folder HoaxBot3000{
    folder StorySquadAI{
        file contestant.py{
            class StorySquadAI{
                class StorySquadBot
                class Personality
                class PersonalityRequestData
            }


            PersonalityRequestData<--personality_directory
            'PersonalityRequestData<--yaml
            'PersonalityRequestData<--bot_context_docs
            webserver <--> StorySquadAI
            Personality -- StorySquadBot
            StorySquadBot -- StorySquadAI
            PersonalityRequestData -- StorySquadAI
        }


    }
            folder data_directory{
                folder personality_directory {
                    file bot.yaml{
                    }
                    file bot_context_docs
                }

                folder other_bot_personalities{
                file others
                }
            }


    rectangle webserver{
    file app.py {
    class app{
    }
    }
    }

    "Tom"--> webserver

    rectangle notion_interface.py{
    class notion_interface
    }


notion_interface --> bot.yaml
"Graig" --> notion_interface
"Jeannine" --> notion_interface
"Tom" --> notion_interface

@enduml

